### PR TITLE
Adjust Tutorial Static Methods

### LINKED ISSUE #40: Failed Function in Tutorial Component
https://github.com/zooniverse/Zooniverse-React-Components/blob/master/src/components/tutorial.jsx#L116

This line needs a `return` or else it fails as an async call.

A couple more line changes are also necessary to have `Tutorial.startIfNecessary` functions running correctly.

### PR DESCRIPTION
**Pull request by wgranger**
Fixes #40 

This should be the last fix required to get tutorials working from this repo. Unfortunately, in creating the first PR for tutorials, I failed to test all use cases for the `startIfNecessary` function (new user, no user, user who has seen the tutorial). This should fix those issues.

### CODE REVIEW

File: src/components/tutorial.jsx [hunk 1]
```diff
@@ -94,26 +94,25 @@ Tutorial.checkIfCompleted = (tutorial, user, preferences) => {
     if (preferences && preferences.preferences && preferences.preferences.tutorials_completed_at && preferences.preferences.tutorials_completed_at[tutorial.id]) {
       return Promise.resolve(preferences.preferences.tutorials_completed_at[tutorial.id]);
     }
+    return Promise.resolve();
   } else {
-    if (completedThisSession[tutorial.id]) {
-      return Promise.resolve(completedThisSession[tutorial.id]);
-    }
+    return Promise.resolve(completedThisSession[tutorial.id]);
```
Comment (srallen) [inline src/components/tutorial.jsx]: Why was the conditional removed?

Comment (wgranger) [reply src/components/tutorial.jsx]: Because if the conditional is not met (because `completedThisSession[tutorial.id]` doesn't exist) then the promise will not resolve and line 105/6 will return undefined at `.then((completed)`, causing `.then` to fail and the code to stop at that line.

Comment (wgranger) [reply src/components/tutorial.jsx]: Here's how it's currently written in PFE w/ Coffeescript https://github.com/zooniverse/Panoptes-Front-End/blob/2e7e67b553940c0a618163d331912840928ca395/app/components/tutorial.cjsx#L39

Comment (srallen) [reply src/components/tutorial.jsx]: Ah, ok. In the coffeescript, the existential operator wasn't being used as it is typically, but rather explicitly cast the value of the `completedThisSession[tutorial.id]` to a boolean. We want the Promise to resolve as `true` or `false`. So I believe the conversion of this line to javascript would be:
`return Promise.resolve(!!completedThisSession[tutorial.id]);`

Comment (srallen) [reply src/components/tutorial.jsx]: Also, line 95:
`return Promise.resolve(!!preferences.preferences.tutorials_completed_at[tutorial.id]);`

Comment (srallen) [reply src/components/tutorial.jsx]: Sorry scratch that, as there are some existential checks in the original for that one too. But I think you understand what needs to change for both. Thanks.

File: src/components/tutorial.jsx [hunk 2]
```diff
@@ -94,26 +94,25 @@ Tutorial.checkIfCompleted = (tutorial, user, preferences) => {
     if (preferences && preferences.preferences && preferences.preferences.tutorials_completed_at && preferences.preferences.tutorials_completed_at[tutorial.id]) {
       return Promise.resolve(preferences.preferences.tutorials_completed_at[tutorial.id]);
     }
+    return Promise.resolve();
```
Comment (srallen) [inline src/components/tutorial.jsx]: This should I think be `Promise.resolve(false)`

File: src/components/tutorial.jsx (hunk 1 above)
Comment (wgranger) [reply src/components/tutorial.jsx]: Ahh, interesting. Ok, looks like I'll need to check out how both these promises resolve. Luckily I have a branch set up on BPL, so I can link the two and make sure any changes work correctly when I'm tinkering.

File: src/components/tutorial.jsx [hunk 3]
```diff
@@ -94,34 +94,36 @@ Tutorial.checkIfCompleted = (tutorial, user, preferences) => {
     if (preferences && preferences.preferences && preferences.preferences.tutorials_completed_at && preferences.preferences.tutorials_completed_at[tutorial.id]) {
       return Promise.resolve(preferences.preferences.tutorials_completed_at[tutorial.id]);
```
Comment (srallen) [inline src/components/tutorial.jsx]: Let's have this static method return the same type consistently in the Promise. Right now if the user does have a stored timestamp for the given tutorial, the promise is returning the datetime string. If not, then it returns false. Let's have this return true, either cast it with a double bang: `Promise.resolve(!!preferences.preferences.tutorials_completed_at[tutorial.id]` or `Promise.resolve(true)`

File: src/components/tutorial.jsx [hunk 4]
```diff
@@ -94,34 +94,36 @@ Tutorial.checkIfCompleted = (tutorial, user, preferences) => {
...
     }
+    return Promise.resolve(false);
   } else {
     if (completedThisSession[tutorial.id]) {
       return Promise.resolve(completedThisSession[tutorial.id]);
     }
+    return Promise.resolve(false);
```
Comment (srallen) [inline src/components/tutorial.jsx]: I think lines 99-102 could be tidied up as just: `Promise.resolve(!!completedThisSession[tutorial.id])` which will return true or false depending on the presence of that id in the object. The above lines did have to have the existential checks first because it is a deeply nested object. This isn't. Also as noted in the above comment, we should be consistent with the type that is returned and here, it should be a boolean.
